import './Home.css'

function AboutSec(props){
    return(
        <>
            <div className="aboutSection" id='about' ref={props.aboutRef}>
                <p>I am <b>Addepalli Jayakar</b>, a proactive and detail-oriented software developer with a strong foundation in technology and a passion for crafting innovative solutions. I had the privilege of working as a <b>Frontend Developer Intern</b> for four months at <b>ZestIOT Technologies</b>, Hyderabad. This experience allowed me to hone my skills in developing user-friendly interfaces while collaborating with a dynamic team to deliver impactful and high-quality projects.</p><br></br>
                <p>I hold a <b>Bachelor's degree in Electronics and Communication Engineering (ECE) from JNTUK</b> and have cultivated extensive hands-on experience in both frontend and backend development. My technical expertise spans <b style={{color:'orange'}}>HTML5</b>, <b style={{color:'blue'}}>CSS3</b>, <b style={{color:'goldenrod'}}>JavaScript</b>, and frameworks such as <b style={{color:'skyblue'}}>React</b> and <b style={{color:'pink'}}>Angular</b> for frontend development. On the backend, I am proficient in <b style={{color:'yellowgreen'}}>Python</b>, <b style={{color:'green'}}>Django</b>, <b style={{color:'purple'}}>SQL</b>,  <b style={{color:'orangered'}}>RabbitMQ</b> and <b style={{color:'red'}}>Redis</b>, enabling me to deliver robust, scalable, and secure applications. My workflow is supported by practical knowledge of version control tools like <b style={{color:'orange'}}>Git</b> and <b style={{color:'blue'}}>GitHub</b>, along with development environments such as <b style={{color:'blue'}}>VS Code</b> and <b style={{color:'yellowgreen'}}>PyCharm</b>.</p><br></br>
                <p>Throughout my journey, I have worked on diverse projects, including <b>automatic plant irrigation systems</b> and <b>e-commerce platforms</b>, which have enhanced my skills in user-centric design, collaboration, and problem-solving. These projects have also strengthened my ability to integrate performance-optimized and secure features into applications.</p><br></br>
                <p>I am deeply committed to continuous learning and professional growth. Recently, I have enhanced my technical repertoire through certifications in <b>Python Full Stack Course</b>, <b>JavaScript Programming</b> and <b>React JS Basics</b>. My achievements, such as a commendable <b>performance in the TCS National Qualifier Test</b>, reflect my dedication to excellence and readiness to tackle new challenges in software development.</p><br></br>
                <p>I am eager to leverage my technical skills and soft skills in communication and teamwork to contribute meaningfully to your esteemed organization's success. Please feel free to reach out via email at <a href='mailto:addepallijayakar@gmail.com' target='_blank' onMouseMove={props.handleMove} onMouseOut={props.handleOut}>addepallijayakar@gmail.com</a> or connect with me on <a href='https://www.linkedin.com/in/addepallijayakar270602/' rel='norefferer' target='_blank' onMouseMove={props.handleMove} onMouseOut={props.handleOut} style={{color:'blue'}}>LinkedIn</a> and <a href='https://github.com/JayakarAddepalli' rel='norefferer' target='_blank' onMouseMove={props.handleMove} onMouseOut={props.handleOut} style={{color:'blue'}}>GitHub</a> to explore potential collaborations.</p>
            </div>
        </>
    )
}

export default AboutSec